### ISSUE TITLE
Additional menu item ruins home page's link address

### ISSUE THREAD

**Issue by 01Kuzma** [JoomShaper/Helix-Joomla#14]
Hello!
I've found a bug related to Helix3. OnePage template was used.
The steps to reproduce it:
Add additional menu item to the top main menu, which leads to a non-main page (for instance link it to a another page which is built with a Sp Page Builder)
Open that page through a main menu, hover over the "HOME" button in the top menu. 
The URL link won't point to the root of the web site, it generates link like this:
#section-id-1501767530280

Only setting the first row to Fluid solves the issue!

Moreover **.active** menu element, which points to an article will be disabled, once that article is opened! It's not clickable and won't refresh the page by click!

**Comment by nayemmajhar** [comment]
add screenshot please

**Comment by 01Kuzma** [comment]
![screen2](https://user-images.githubusercontent.com/569504/29521994-6fe4b5be-8690-11e7-8d90-73d9da4990ea.jpg)

**Comment by 01Kuzma** [comment]
Any news/progress?

**Comment by rifatwahid** [comment]
Hi,
One Page template developed by Helix3 and SP Page Builder. We upgrade this template helix2 to helix3.

- Thanks

**Comment by 01Kuzma** [comment]
Hi!
Haven't understood. This template will be upgraded to helix version 3 in the future? Now it's based on version 2.3 as I understand...

**Comment by ittoufiq** [comment]
Hi there, We don't have the plan to upgrade. Thanks
